### ISSUE TITLE
Missing/incorrect files for preprocessing

### ISSUE THREAD

**Issue by oentaryorj** [aws-samples/amazon-sagemaker-amazon-routing-challenge-sol#1]
Hi,

Thanks for this great repository.

I downloaded the AWS Last-Mile Challenge dataset (step 2; via `aws s3 sync --no-sign-request s3://amazon-last-mile-challenges/almrrc2021/ ./data/`), and am now trying to preprocess the data (step 3). However, it seems that some file names are missing/inconsistent when I tried to run the script below:
```
train_data_dir=almrrc2021-data-training
eval_data_dir=almrrc2021-data-evaluation

# generate package information in Parquet (training)
python preprocessing.py --act gen_route --data_dir  data/${train_data_dir}
# generate travel time matrix for all stops in a route (training)
python preprocessing.py --act gen_dist_mat --data_dir  data/${train_data_dir}
# generate zone information for each stop (training)
python preprocessing.py --act gen_zone_list --data_dir  data/${train_data_dir}
# generate ground-truth zone sequence for each route
python preprocessing.py --act gen_actual_zone --data_dir  data/${train_data_dir}
# generate package information in Parquet (evaluation)
python preprocessing.py --act gen_route --data_dir  data/${eval_data_dir}
# generate travel time matrix for all stops in a route (evaluation)
python preprocessing.py --act gen_dist_mat --data_dir  data/${eval_data_dir}
# generate zone information for each stop (evaluation)
python preprocessing.py --act gen_zone_list --data_dir  data/${eval_data_dir}
```

I noticed that the JSON files under `almrrc2021-data-training` folder are slightly different from those under `almrrc2021-data-evaluation`, e.g., `almrrc2021-data-training/model_score_inputs/new_actual_sequences.json`  vs. `almrrc2021-data-evaluation/model_score_inputs/eval_actual_sequences.json`. 

Would it be appropriate to rename the former to `eval_actual_sequences.json` in this case? Or is it better to handle this in `preprocessing.py`, e.g., the `LMC_ACTUAL_FN` variable?

**Comment by oentaryorj** [comment]
It seems that we also need to manually create `data` and `distance_matrix` subfolders. Would be good to handle this in `preprocessing.py` as well.

Nevertheless, after doing the above, I still see this error:
```
Traceback (most recent call last):
  File "preprocessing.py", line 459, in <module>
    raise Exception('Missing the name of the parquet file (e.g. lmc_route_full_1637316909.parquet) generated by the gen_route action')
```

**Comment by chenwuperth** [comment]
Hi @oentaryorj , thank you very much for reporting the issue. Can you please git pull the latest from the main branch?

I have fixed the file naming issues in the code, so depends on the `--mode` argument, it will change the file name (in fact sub-directory name) accordingly.
I have also added the auto-creation of sub-folder `distance_matrix` and `zone_list`. The sub-folder `data` is not auto-created only because it is possible the this folder is outside of the git repository (depends where the dataset is downloaded to). So you could use the argument `--data_dir` to tell the preprocessing script where the `train` or `eval` dataset is
The second error was due to the missing parameter `--pkfn`, and I have added that in the README.md instruction. This file is only generated after you run the `python preprocessing.py --act gen_route ` 
Please let me know if you see any other problems. Thanks again for your help.
